Auth add providers 23.06.2023
nicitaacom/22_aer pull request #9
Opened 2023-06-27 17:27 UTC by arifm6

Set up backend providers for github and google. One potential issue is that duplicate emails on different providers is not allowed. This is standard in a lot of authentication systems.

2023-06-27 19:21 UTC, Nicitaa requested changes
Fontend design required
For now its fine but facebook provider needed (so do auth with facebook)
![image](https://github.com/Nicitaa/22_aer/assets/39565703/acb6831c-690b-4a91-b9bb-ad5cf8511f41)

Also I would like name context as context - not with ctx

Delete my auth with github provider in database - so I can test how auth with google works
![image](https://github.com/Nicitaa/22_aer/assets/39565703/53306b2a-7e11-4da6-b3db-934d570ea2a6)

2023-06-27 19:21 UTC, nicitaacom commented on src/pages/home.tsx
Why you created home.tsx - we don't need it

2023-06-27 19:21 UTC, nicitaacom commented on src/pages/index.tsx
Specify const name please
const hello - doesn't tell me anything

2023-06-27 19:21 UTC, Nicitaa commented on src/pages/index.tsx
Also infinity tRPC loading
![image](https://github.com/Nicitaa/22_aer/assets/39565703/2c781ce6-62c6-43b2-978d-6efb16fc932f)

2023-06-28 00:57 UTC, arifm6 commented on src/pages/index.tsx
this is just for testing. hello is the greeting msg.

2023-06-28 09:52 UTC, Nicitaa approved these changes
I approve it - so we will up to date with development branch
Auth with google and github works fine - fix with facebook needed

2023-06-28 09:58 UTC, merged